--Total revenue generated by each seller
SELECT
    seller_id,
    SUM(price) AS total_revenue
FROM order_items
GROUP BY seller_id
ORDER BY total_revenue DESC
LIMIT 10;

--Number of items sold by each seller
select seller_id,count(*) as item_sold
from order_items
group by seller_id 
order by item_sold desc 
limit 10;

--Number of orders handled by each seller
select seller_id,count(distinct order_id) as order_handled
from order_items
group by seller_id 
order by order_handled desc
limit 10;

--revenue by seller state 
select s.seller_state,sum(oi.price) as total_revenue
from order_items oi 
join sellers s on oi.seller_id = s.seller_id 
group by s.seller_state 
order by total_revenue desc;

--Average review score for each seller
select oi.seller_id, round(avg(t.review_score),2) as average_review_score, count(distinct oi.order_id) as total_order
from order_items oi
join order_reviews t on oi.order_id = t.order_id 
group by oi.seller_id 
having count(distinct oi.order_id) >=10
order by average_review_score desc;


