--Total revenue generated by each seller
SELECT
    seller_id,
    SUM(price) AS total_revenue
FROM order_items
GROUP BY seller_id
ORDER BY total_revenue DESC
LIMIT 10;

--Number of items sold by each seller
select seller_id,count(*) as item_sold
from order_items
group by seller_id 
order by item_sold desc 
limit 10;

--Number of orders handled by each seller
select seller_id,count(distinct order_id) as order_handled
from order_items
group by seller_id 
order by order_handled desc
limit 10;